package model.layouts

class Btns {
    companion object {

        val SHIFT = ButtonDescription( Ops.SHIFT, Ops.UNSHIFT )
        val EVAL =  ButtonDescription( Ops.EVAL )
        val x =  ButtonDescription( Ops.X )
        val y =  ButtonDescription( Ops.Y )
        val z =  ButtonDescription( Ops.Z )
        val STO =  ButtonDescription( Ops.STO )
        val ENTER_DROP =  ButtonDescription( Ops.ENTER, Ops.DROP, 2f )
        val SWAP_ROLL =  ButtonDescription( Ops.SWAP, Ops.ROLL )
        val UNDO_REDO =  ButtonDescription( Ops.UNDO, Ops.REDO )
        val i_ABS =  ButtonDescription( Ops.i, Ops.TODO )
        val D0 =  ButtonDescription( Ops.DIGIT(0) )
        val D1 =  ButtonDescription( Ops.DIGIT(1) )
        val D2 =  ButtonDescription( Ops.DIGIT(2) )
        val D3 =  ButtonDescription( Ops.DIGIT(3) )
        val D4 =  ButtonDescription( Ops.DIGIT(4) )
        val D5 =  ButtonDescription( Ops.DIGIT(5) )
        val D6 =  ButtonDescription( Ops.DIGIT(6) )
        val D7 =  ButtonDescription( Ops.DIGIT(7) )
        val D8 =  ButtonDescription( Ops.DIGIT(8) )
        val D9 =  ButtonDescription( Ops.DIGIT(9) )
        val DA =  ButtonDescription( Ops.DIGIT(10) )
        val DB =  ButtonDescription( Ops.DIGIT(11) )
        val DC =  ButtonDescription( Ops.DIGIT(12) )
        val DD =  ButtonDescription( Ops.DIGIT(13) )
        val DE =  ButtonDescription( Ops.DIGIT(14) )
        val DF =  ButtonDescription( Ops.DIGIT(15) )
        val D0000 =  ButtonDescription( Ops.DIGIT(0), Ops.digits("0000", listOf(0,0,0,0)) )
        val D0001 =  ButtonDescription( Ops.DIGIT(1), Ops.digits("0001", listOf(0,0,0,1)) )
        val D0010 =  ButtonDescription( Ops.digits("0010", listOf(0,0,1,0)) )
        val D0011 =  ButtonDescription( Ops.digits("0011", listOf(0,0,1,1)) )
        val D0100 =  ButtonDescription( Ops.digits("010", listOf(0,1,0,0)) )
        val D0101 =  ButtonDescription( Ops.digits("0101", listOf(0,1,0,1)) )
        val D0110 =  ButtonDescription( Ops.digits("0110", listOf(0,1,1,0)) )
        val D0111 =  ButtonDescription( Ops.digits("0111", listOf(0,1,1,1)) )
        val D1000 =  ButtonDescription( Ops.digits("1000", listOf(1,0,0,0)) )
        val D1001 =  ButtonDescription( Ops.digits("1001", listOf(1,0,0,1)) )
        val D1010 =  ButtonDescription( Ops.digits("1010", listOf(1,0,1,0)) )
        val D1011 =  ButtonDescription( Ops.digits("1011", listOf(1,0,1,1)) )
        val D1100 =  ButtonDescription( Ops.digits("1100", listOf(1,1,0,0)) )
        val D1101 =  ButtonDescription( Ops.digits("1101", listOf(1,1,0,1)) )
        val D1110 =  ButtonDescription( Ops.digits("1110", listOf(1,1,1,0)) )
        val D1111 =  ButtonDescription( Ops.digits("1111", listOf(1,1,1,1)) )
        val DIVIDE_MOD =  ButtonDescription( Ops.DIVIDE, Ops.TODO )
        val MULTIPLY_REM =  ButtonDescription( Ops.MULTIPLY, Ops.TODO )
        val NEGATE =  ButtonDescription( Ops.NEGATE )
        val CLEAR =  ButtonDescription( Ops.CLEAR )
        val SUBTRACT =  ButtonDescription( Ops.SUBTRACT )
        val TODO =  ButtonDescription( Ops.TODO, Ops.TODO )
        val POINT =  ButtonDescription( Ops.POINT )
        val POW = ButtonDescription( Ops.POW )
        val EXP =  ButtonDescription( Ops.EXP )
        val ADD =  ButtonDescription( Ops.ADD )
    }
}